# Generated by Django 4.1.6 on 2023-02-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='connection_code',
            field=models.SlugField(unique=True),
        ),
    ]
