# Generated by Django 4.1.6 on 2023-02-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quizresult_questionresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=models.ManyToManyField(related_name='correct_answers', to='quiz.answer'),
        ),
    ]
