# Generated by Django 4.1.6 on 2023-02-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_alter_question_correct_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answers',
            field=models.ManyToManyField(blank=True, related_name='correct_answers', to='quiz.answer'),
        ),
    ]
