# Generated by Django 4.1.6 on 2023-02-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresult',
            name='chosen_answers',
            field=models.ManyToManyField(blank=True, related_name='chosen_answers', to='quiz.answer'),
        ),
    ]
