# Generated by Django 4.1.6 on 2023-04-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_questionresult_chosen_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
    ]
