# Generated by Django 4.1.6 on 2023-04-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_remove_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
