# Generated by Django 4.1.5 on 2023-05-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_quiz_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answers',
        ),
    ]
